# These are supported funding model platforms

github: [W-N-R, Azher Bashir]
patreon: W_N_R
open_collective:  W-N-R
ko_fi: W-N-R
tidelift: W-N-R
community_bridge:  W-N-R
wordpress: https://wnr01.wordpress.com/
custom: https://github.com/W-N-R
